name: Generate Balearic Islands Weather Maps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # 06:00 UTC daily

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: generate-maps
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate maps
        env:
          CI: true
        run: |
          python "generar_mapa_baleares.py"
          python "generar_minmax_baleares.py"

      - name: Prepare pages content
        run: |
          mkdir -p generated
          cp -f mapa_baleares_openmeteo.png generated/
          cp -f mapa_baleares_min.png generated/
          cp -f mapa_baleares_max.png generated/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: meteo-illes-maps
          path: |
            mapa_baleares_openmeteo.png
            mapa_baleares_min.png
            mapa_baleares_max.png
          if-no-files-found: error
          retention-days: 7
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: generated

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

